site_name: Django Conman
theme: 'material'
pages:
  - Installation: index.md
  - Routes: routes.md
  - Handlers: handlers.md
  - Redirects: redirects.md
  - Admin integration: admin.md
  - Reference: reference.md
  - Contribution: contribution.md
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
repo_name: 'meshy/django-conman'
repo_url: 'https://github.com/meshy/django-conman'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/meshy/django-conman'
