site_name: Django Conman
theme: 'material'
pages:
  - Installation: index.md
  - Tutorials:
    - Creating custom routes TODO: tutorials/custom_routes.md
    - Basic HTML TODO: tutorials/basic_html.md
    - Rich text TODO: tutorials/rich_text.md
    - Application content TODO: tutorials/app_content.md
  - Topics:
    - Admin integration: topics/admin.md
    - Handlers TODO: topics/handlers.md
    - Redirects TODO: topics/redirects.md
    - Routes TODO: topics/routes.md
  - API Reference:
    - Route: reference/route.md
    - Handlers TODO: reference/handlers.md
  - Contribution: contribution.md
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
repo_name: 'meshy/django-conman'
repo_url: 'https://github.com/meshy/django-conman'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/meshy/django-conman'
