site_name: Django Conman
theme: 'material'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
repo_name: 'meshy/django-conman'
repo_url: 'https://github.com/meshy/django-conman'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/meshy/django-conman'
