import factory

from .. import models


class NodeFactory(factory.DjangoModelFactory):
    """Create instances of Node for testing."""
    class Meta:
        model = models.Node


class RootNodeFactory(NodeFactory):
    """Create a Node with no parent and an empty slug."""
    slug = ''
    parent = None

    class Meta:
        django_get_or_create = ['slug']


class ChildNodeFactory(NodeFactory):
    """Create a Node with an autogenerated slug and parent Node."""
    parent = factory.SubFactory(RootNodeFactory)
    slug = factory.Sequence('slug{}'.format)
