import factory

from .. import models


class RouteFactory(factory.DjangoModelFactory):
    """Create instances of Route for testing."""
    class Meta:
        model = models.Route


class RootRouteFactory(RouteFactory):
    """Create a Route with no parent and an empty slug."""
    slug = ''
    parent = None

    class Meta:
        django_get_or_create = ['slug']


class ChildRouteFactory(RouteFactory):
    """Create a Route with an autogenerated slug and parent Route."""
    parent = factory.SubFactory(RootRouteFactory)
    slug = factory.Sequence('slug{}'.format)
