# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0002_urlredirect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlredirect',
            options={'verbose_name': 'URL redirect'},
        ),
        migrations.AlterField(
            model_name='routeredirect',
            name='permanent',
            field=models.BooleanField(default=False, help_text='If permanent, this redirect will be cached by browsers.'),
        ),
        migrations.AlterField(
            model_name='routeredirect',
            name='target',
            field=models.ForeignKey(help_text='Browsers will be redirected to this route.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='routes.Route'),
        ),
        migrations.AlterField(
            model_name='urlredirect',
            name='permanent',
            field=models.BooleanField(default=False, help_text='If permanent, this redirect will be cached by browsers.'),
        ),
        migrations.AlterField(
            model_name='urlredirect',
            name='target',
            field=models.URLField(help_text='Browsers will be redirected to this URL.', max_length=2000),
        ),
    ]
